name: build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Setup Go
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15.x' # The Go version to download (if necessary) and use.
        
    # Run build of the application
    - name: Run build
      run: go build . 
      
    # Run gofmt on the code
    - name: Run gofmt
      run: gofmt -d
    
    # Run testing on the code
    - name: Run testing
      run: |
        go test -v -race -coverprofile=coverage.txt ./...
        go test -race -json ./... > report.json
        curl -s https://codecov.io/bash | bash
